### ISSUE TITLE
Blank screen after signing in to roku

### ISSUE THREAD

**Issue by fakeid30** [jellyfin-archive/jellyfin-roku-legacy#103] opened 2019-12-26 15:59 UTC
**Describe the bug**
After logging in to jellyfin I see a blank screen when I click a collection. 

**To Reproduce**

1. Go to Collection
2. Click on Movies
3. See error

**Expected behavior**
See a list of titles

**Logs**
Don't know how to obtain log from roku ultra 2018 model

**Screenshots**
https://imgur.com/a/iSGHLho

**Additional context**
Using a roku ultra 2018 model and wired internet.

**Comment by cewert** [comment] 2020-02-23 04:31
Is this still happening? I believe this was fixed

**Comment by fakeid30** [comment] 2020-02-23 12:10
@cewert I still have the problem . The server is behind a reverse proxy , can that affect this bug ?

**Comment by cewert** [comment] 2020-02-23 16:45
I don't use a reverse proxy so I'm not sure.

- Are you using the latest code from this repo? There have been a lot of updates since your OP.
- Is this media accessible using any other client? (android, web UI etc)
- To view crash reports and logs type `telnet ROKU-IP 8085`. Please give this a try if using the latest code doesn't fix the issue.

**Comment by bisby** [comment] 2020-02-23 17:54
Is your collection TV show collections by any chance?

**Comment by fakeid30** [comment] 2020-02-23 18:14
@bisby all collections

@cewert 

- Yes latest code
- Yes accessible

Here is the telnet : https://pastebin.com/Vd6fJPm2

**Comment by cewert** [comment] 2020-02-23 18:30
`ERROR: roUrlTransfer.GetToString: Sync-wait interrupted: pkg:/source/api/baserequest.brs(67)`

Seems to be some kind of connection issue

**Comment by cewert** [comment] 2020-02-23 18:38
Are you using https? Using the same server URL and user as the client that worked? Which client?

Maybe it is your reverse proxy after all. Could you share your config?

**Comment by bisby** [comment] 2020-02-23 18:47
... It looks like we're getting `req.GetToString()` twice in that location. Is there a reason we couldn't just parse the output of the first request?

**Comment by cewert** [comment] 2020-02-23 19:03
@bisby that is a great point.

I replaced line 67 with `json = ParseJson(data)` and everything loaded just fine. A bit faster maybe

**Comment by cewert** [comment] 2020-02-23 19:22
@fakeid30 can you do a git pull and try again please?

**Comment by fakeid30** [comment] 2020-02-25 07:00
@cewert Still same issue, here is the telnet : https://pastebin.com/SKi6wGeQ

- Are you using https? Using the same server URL and user as the client that worked? Which client?

Yes . Android, Kodi, Chromecast & Web client works.

**Comment by fakeid30** [comment] 2020-02-25 07:00
If needed I can create an account for you to test (if that's easier).

**Comment by Alcatraz077** [comment] 2020-03-02 01:55
I'm having a similar issue, but only occurs when I select a Collection that includes TV episodes, rather than just movies.

**Comment by bisby** [comment] 2020-03-02 01:59
Thanks for that insight. There is definitely some bits of collections code that (incorrectly) assumes collections will contain only movies.

**Comment by Alcatraz077** [comment] 2020-03-02 02:12
No problem, I'm digging through the code tonight trying to find a way to fix it. 

Edit: I should add I know absolutely no BrightScript, so this may take awhile. Apologies.

**Comment by fakeid30** [comment] 2020-03-21 07:43
Update : 

After pulling in the latest changes , Now I see movies in the homescreen and able to play it. Although when I click on movie collection I see a popup saying "This media type has not yet been implemented: Movies"

**Comment by neilsb** [comment] 2020-03-23 09:38
Can I just check a couple of things please

1. Is the error message exactly as above, or is it "This **library** type is not yet implemented"? - Just to we're at the right but in the code )

2. On the dashboard, you can see the Movies collection, and it shows the same image as you see on the website?

3. Is the language of your systems English (Web and Roku)?

4. Do you have a TV Shows Collection type, and does it work or does the same thing happen?

Thanks.

**Comment by fakeid30** [comment] 2020-03-23 09:55
Hello @neilsb 

>     1. Is the error message exactly as above, or is it "This **library** type is not yet implemented"? - Just to we're at the right but in the code )

You are right, This **library** type is not yet implemented is correct error that I am seeing.

>     2. On the dashboard, you can see the Movies collection, and it shows the same image as you see on the website?

it shows no image, just a generic TV logo. 

>     3. Is the language of your systems English (Web and Roku)?

Yes

>     4. Do you have a TV Shows Collection type, and does it work or does the same thing happen?

Same thing 

but I can play from Next Up , Latest in Movies and Latest in TV shows now.

**Comment by neilsb** [comment] 2020-03-23 10:24
Hi @fakeid30,

So the problem is the data the server is sending down to the roku client for your list of collections.  Plainly the client is not handling your collections correctly, but I cannot replicate it.

What would be really helpful is json your server sends, but in order to get this you first need to get your internal UserId from your server.  I'll drop an email to the address in your GitHub profile rather than have a conversation here with instructions.

**Comment by fakeid30** [comment] 2020-03-23 15:10
@neilsb thanks for your email and I have sent you the json .

**Comment by neilsb** [comment] 2020-03-23 16:21
@fakeid30 Thanks for that.  Submitted a PR which should fix it - so when that's merged that should have resolved that issue.  Thanks for your help.

**Closed as completed** 2020-03-23 17:41 UTC
Labels: bug, info-needed
