### ISSUE TITLE
Home Page is sometimes sticky and won't disappear.

### ISSUE THREAD

**Issue by Artiume** [jellyfin-archive/jellyfin-roku-legacy#288] opened 2020-11-11 15:35 UTC
Home Page is sometimes sticky and won't disappear.

![20201111_102625](https://user-images.githubusercontent.com/20715731/98830496-7834da00-2408-11eb-9324-4b132bba4826.jpg)

I had suspected screensaver but I just had it occur after an episode ending without going to screensaver. 1st episode caused bug, 2nd episode was fine, 3rd episode caused it again so nothing consistent.

**Comment by neilsb** [comment] 2020-11-11 15:44
Actually, thinking about it the Movies Screen background has a high Opacity set to show it faded, and from your screenshot it looks like that's  on top of the Home Page rows.  So probably just need to add a solid background behind the Movie Background.   Doesn't explain why it's intermittent though.

**Comment by Artiume** [comment] 2020-11-11 20:37
yeah, after a few more episodes, it's happened twice more. 40% chance of it happening? another shot for live tv page 
![20201111_110746](https://user-images.githubusercontent.com/20715731/98861747-c90df800-2433-11eb-8d53-1ddcd09267b5.jpg)

**Comment by neilsb** [comment] 2020-11-13 13:55
This seems to occur when a item is played directly from the home screen without going through any other screens (e.g. Continue Watching or Next Up) and then finishes and automatically returns to the home screen.   

Pressing back to return to the home screen while playing the video does not cause the problem to appear.

**Comment by Artiume** [comment] 2020-11-13 14:33
makes sense.  has it been consistent for you?  perhaps my testing was causing the inconsistency.

**Comment by neilsb** [comment] 2020-12-02 16:49
That seems to be a consistent way of reproducing it.  It's to do with it previously focused screens, and removing existing screens from the "stack" when it goes to display a new one.   Playing a video directly from the home screen without showing another screen in between messes it up.

**Comment by jimdogx** [comment] 2022-11-09 14:42
Is this still an issue?  I have not been able to reproduce this with the latest builds.

**Comment by neilsb** [comment] 2022-11-09 15:13
I suspect with the new Page Display stuff that was put in that this is no longer an issue.  I would say we can close this and re-open it if it's seen again.

**Comment by jimdogx** [comment] 2022-11-09 15:25
Closing.  @Artiume let us know if this is still an issue.

**Closed as completed by jimdogx** 2022-11-09 15:25 UTC
Labels: bug
