### ISSUE TITLE
subtitles added successfully but are not visible while playing

### ISSUE THREAD

**Issue by cpankonien** [jellyfin-archive/jellyfin-roku-legacy#358] opened 2021-01-19 22:57 UTC
subtitles added but are not visible.

subtitles were added using the Open Subtitles plugin, but I have also manualy copied the .srt file to the same dir as the video file and named it exactly the same as the .mkv except with .srt file extension.

OS: Ubuntu 20.04.1
Virtualization: none
Clients: roku, browser
Browser: latest Chrome
Jellyfin Version: 10.7rc2
Playback: all
Installed Plugins: AudioDB, MusicBrainz, OMDb, Open Subtitles
Reverse Proxy: none
Base URL: none
Networking: n/a
Storage: local

To Reproduce

start episode
click asterisk, set options "Captions mode: on always" and "Caption track: 1 of 1 (English)
during play, hit down arrow, select subtitle track "English"
Expected behavior - subtitles play
So...subtitles added successfully and selected successfully but do not work. Subtitles do work in web player.

Logs
none

Screenshots
n/a
Additional context
I have verified that the .srt file is in the location indicated, and contains subtitle text.

Subtitles work correctly in web viewer but not on roku

**Comment by neilsb** [comment] 2021-02-22 12:14
Do they fail on all Media via the Roku, or just some?   Can you also let me know if they are shown when using the web player, for titles that fail on the Roku?

**Comment by Drose221193** [comment] 2021-03-13 16:52
I can confirm I am having the same issue. I have had the Roku subtitles work in the past, but it was fairly inconsistent. I saw this issue so decided to test various movies and shows. All media seems to not be displaying any subtitles. The media I tested works on the web player as well as Android tv. I have subtitle settings set to always play so they are automatically selected when I play media. I also tried toggling the subtitles off and on while the media was playing and that did not work.

**Comment by rystaf** [comment] 2021-03-15 23:27
Same thing happened to me after upgrading jellyfin to 10.7.0. Was working fine before. Unsure what version I was on before the upgrade (docker latest tag strikes again). Subtitles work on Intune on AppleTV and in the web player. No subtitle for any media on roku (captions on always, down arrow english). tried the channel from the store as well as the dev version from github.

**Comment by crass** [comment] 2021-04-06 06:48
I believe I'm having the same issue on Jellyfin 10.7.1 (docker image) with my Roku Streaming stick. I've tried both the main and beta channels. I am testing with an mkv which has two SRT subtitle files one for english and one for spanish. I have them named properly in the same directory as the mkv. Also the subtitle files are encoded as tracks in the mkv. So there are a total of 4 SRT subtitle tracks recognized (2 in the file and 2 outside). The web client detects and displays all 4 subtitle files. The roku detects the 4 "caption tracks", however none are displayed when selected when the "captions mode" is set to "On always".

I don't see any obvious issues in the Jellyfish server logs. Is there a way to get debug logs from a roku devices? Or something I can do to help debug this issue?

**Comment by neilsb** [comment] 2021-04-06 07:15
@crass I believe #385 will resolve this issue, but external verification will be useful.

In the 10.7 release there was a change to the API that caused sub titles (certainly .srt) to no longer work. [An issue](https://github.com/jellyfin/jellyfin/issues/5581) was raised on server to re-introduce backward compatibility and has been closed, so the next point release of 10.7 _should_ also fix this problem.

We've currently got a release in the approval pipeline with Roku, but it's taking longer than usual.  But whichever happens first (next 10.7 release or Roku approval) should mean the issue is hopefully closed.

**Comment by crass** [comment] 2021-04-06 07:57
Hmm, am I incorrect in thinking the JellyfinBeta channel is the what will be the new Roku release? In other words, shouldn't subtitles be working in the beta channel?

**Comment by neilsb** [comment] 2021-04-06 08:04
Up to now we haven't consistently done beta releases prior to releasing to the live channel.  This a process I think we're going to try and follow more closely however.

That said, we published a Beta update a few days ago, but for some reason the Beta channel is not updating on clients.  It's currently an old version you're getting via the beta link (1.3.5 - earlier than the live version).  Hopefully we'll get to the bottom of this shortly.

**Comment by neilsb** [comment] 2021-04-06 14:37
@crass That is the Beta version issue resolved, and should contain the Subtitle fix.  Would appreciate it if you let us know if it resolves it for you when you get a chance.

**Comment by crass** [comment] 2021-04-07 05:39
Just tested and it does indeed work. Thanks for the hard work!

**Comment by rangerxusa** [comment] 2021-04-09 18:02
Been trying out Plex last couple weeks. Decided to also try out JellyFin as well. 
JellyFin is very nice open source alternative.
Only show stopper so far was no external .srt subtitles on Roku devices.

Subscribed to Roku JellyFinBeta channel.
Subtitles are working fine now.

Thanks!

**Comment by neilsb** [comment] 2021-04-12 07:08
Note Server v10.7.2 has now been released, that should resolve the text subtitle issue with the current live client.  We are still waiting for approval for the Roku Channel Store the the updated client.

**Comment by neilsb** [comment] 2021-04-20 06:53
The 10.4.7 release available in to store should resolve the srt subtitles issue. Burn in subtitles (covered in other open issues) are scheduled to be resolved in the next release probably around the start of May.

**Closed as completed by neilsb** 2021-04-20 06:53 UTC
Labels: bug
