### ISSUE TITLE
Roku not displaying multiple video formats like webclient

### ISSUE THREAD

**Issue by pinovecs** [jellyfin-archive/jellyfin-roku-legacy#413] opened 2021-04-08 00:13 UTC
**Describe the bug**
Roku client does not display two video formats when available in same folder (ex 4K and 1080p) and defaults to only 1080p version of video.  Following Jellyfin server instructions on how to support multiple video formats.

**To Reproduce**

1. Place two movie files in the same movie folder 1 - 4K format and one 1080p
Ex:  Folder name:   Iron Man (2008)
      Files in folder:  Iron Man (2008) - HD.mkv
                              Iron Man (2008) - UHD.mkv

2. PC Web Client will see both formats as the same movie and allow user to choose format to display.
3. Roku Client only displays the 1080p version of the video.
4. No option to select
5. Can only play 4K file by moving 1080p to a folder that can not be scanned.

**Expected behavior**
Client should allow the choice of format.

**Logs**
None

**Screenshots**
If required please let me know.

**Additional context**
N/A

**Comment by neilsb** [comment] 2021-04-08 10:55
Think this may be a duplicate of #280.

**Comment by pinovecs** [comment] 2021-04-08 11:51
Neil, you are correct.  I apologize.  I'd looked through the other bug reports (but only by their titles) and missed that these are the same.

Chris

**Comment by neilsb** [comment] 2021-04-08 12:33
> Neil, you are correct. I apologize. I'd looked through the other bug reports (but only by their titles) and missed that these are the same.

No problem at all.  I'll just close this issue then in favour of #280.  Can keep tabs on it in that issue.

**Closed as completed by neilsb** 2021-04-08 12:33 UTC
Labels: bug
