### ISSUE TITLE
Error: This library type is not yet implemented: music.

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-roku-legacy#263] opened 2020-08-03 01:40 UTC
**Describe the bug**

**To Reproduce**

1. Open Jellyfin
2. Click on a song or album

**Expected behavior**

*music plays normally on iOS and web client. Only device I can test on(besides Roku client).

**Logs**

**Screenshots**

**Additional context**

**Comment by anthonylavado** [comment] 2020-08-03 02:25
Duplicate of #124

**Closed as completed by anthonylavado** 2020-08-03 02:25 UTC
Labels: bug
