### ISSUE TITLE
Attempt to use a non-numeric array index not allowed. pkg:/components/tvshows/TVListDetails.brs(43)

### ISSUE THREAD

**Issue by lpukatch** [jellyfin-archive/jellyfin-roku-legacy#567] opened 2022-04-17 18:03 UTC
**Describe the bug**
When loading a season of a show the app is crashing back to the roku home screen. From the logs it looks like it's trying to index itemData.mediaStreams while videoIdx or audioIdx is invalid

**To Reproduce**
Open a series where Jellyfin hasn't extracted the video or audio stream data for one of the shows in the series. The details error and it crashes back to the home page.

**Logs**
Current Function:
033:          for i = 0 to itemData.MediaStreams.Count() - 1
034:              if itemData.MediaStreams[i].Type = "Video" and videoIdx = invalid
035:                  videoIdx = i
036:              else if itemData.MediaStreams[i].Type = "Audio" and audioIdx = invalid
037:                  audioIdx = i
038:              end if
039:              if videoIdx <> invalid and audioIdx <> invalid then exit for
040:          end for
041:*         m.top.findNode("video_codec").text = tr("Video") + ": " + itemData.mediaStreams[videoIdx].DisplayTitle
042:          m.top.findNode("audio_codec").text = tr("Audio") + ": " + itemData.mediaStreams[audioIdx].DisplayTitle
043:          m.top.findNode("video_codec").visible = true
044:          m.top.findNode("audio_codec").visible = true
045:      else
Source Digest(s): 
pkg: dev 1.4.12 c57341a11381070d7348fa07f053eac9 Jellyfin

Attempt to use a non-numeric array index not allowed. (runtime error &he8) in pkg:/components/tvshows/TVListDetails.brs(41)
Backtrace:
#0  Function itemcontentchanged() As Void
   file/line: pkg:/components/tvshows/TVListDetails.brs(41)
Local Variables:
global           Interface:ifGlobal
m                roAssociativeArray refcnt=2 count:3
item             roSGNode:TVEpisodeData refcnt=1
itemdata         roAssociativeArray refcnt=1 count:26
indexnumber      roString (2.1 was String) refcnt=1 val:"2. "
videoidx         Invalid
audioidx         Invalid
i                Integer val:0 (&h0)

**Comment by whiteowl3** [comment] 2022-04-19 19:51
duplicate of #537 
please consider moving your input to the existing issue.

**Comment by neilsb** [comment] 2022-04-25 16:20
@lpukatch  - Thanks for you report, but just closing this as duplicate of #537.  You can subscribe to that issue for updated.

**Closed as completed by neilsb** 2022-04-25 16:20 UTC
Labels: bug
