### ISSUE TITLE
Main screen keep switching.

### ISSUE THREAD

**Issue by Alliyance** [jellyfin-archive/jellyfin-roku-legacy#1583] opened 2023-12-16 00:16 UTC
## Software Versions

- Jellyfin Server Version:10.8.13  
- Roku Client Version:
2.0.0  

## Describe the bug

Usually my first row is Latest movies and fallow by Latest series. But for some unknown reason, some times that order is switch to the Latest series on top. 

## How To Reproduce

By closing the application and open it. 

## Expected behavior

Should stay with the original lookout with the Latest movies on top. 

## Logs
None 

## Screenshots
None 

## Connection Information

- Is server local or remote?
- Is server connection HTTP or HTTPS?

**Comment by cewert** [comment] 2023-12-16 02:08
duplicate of #1578

**Closed as completed by cewert** 2023-12-16 02:08 UTC
Labels: duplicate
