### ISSUE TITLE
Error when Selecting a Library on Latest Build as of today 7 pm central US

### ISSUE THREAD

**Issue by bmcgonag** [jellyfin-archive/jellyfin-roku-legacy#96] opened 2019-12-07 01:28 UTC
**Describe the bug**
I login to Jellyfin from my Roku, and then select the TV Shows library.  I am momentarily shown an error message that immediately goes away unless I hold down the OK button on the remote. 

The error message says 

> This library type is not yet implemented: tvshows

I have the latest 10.4.2 Jellyfin server, and it works in the browser. 

I have all access to all libraries (only have a TV Shows library right now)

This was working with the previous version with no issue.

**To Reproduce**

1. Install the latest build from github.
2. Enter all server info and credentials.
3. Open Jellyfin app on Roku
4. Notice the TV Shows library is there
5. Select that library.
6. See a briefly shown message stating the same as above.  
7. Hold the OK button down on the Roku remote to get the error message to remain on the screen.
8. Release the OK button and the message goes away, but the TV Shows library is not opened.

**Expected behavior**
Selecting any library will allow me into the library assuming I have access permissions on the server.

**Logs**

Tell me how and where to get logs, and I'm happy to provide them.

**Screenshots**
![jellyfin-rok-error](https://user-images.githubusercontent.com/7346620/70366661-94c2ac80-185e-11ea-872b-c66f4ac4c69f.JPG)

**Additional context**
Went back to commit b51444 in Git history, and that is where I can access my TV Shows library and see all the shows listed.  Not sure this helps, but looks like some major re-factoring is happening...so maybe it's best if I hold off on updating past this for a while?

**Comment by bisby** [comment] 2019-12-07 02:11
"Not yet implemented" means we're aware that we haven't build the functionality yet. So not a bug. but a feature request "implement tvshows". Which is done, but not merged yet.

Duplicate of #91 and fixed by #94

**Closed as completed by bisby** 2019-12-07 02:11 UTC
Labels: duplicate, enhancement

**Comment by bisby** [comment] 2019-12-07 02:50
#94 is merged, you should be able to pull again and have it work.
