### ISSUE TITLE
Bluetooth Audio through phone is unstable

### ISSUE THREAD

**Issue by qman1198** [jellyfin-archive/jellyfin-roku-legacy#995] opened 2023-01-30 21:30 UTC
**Software Versions**
Jellyfin Server Version: 10.8.9
Roku Client Version: 1.6.3

Roku Express HD 3930X

**Describe the bug**
When connected to Jellyfin Roku audio through Roku app's private listening feature, connected over Bluetooth to Apple Airpods Pro, after a few minutes audio starts to cut out. By 10 minutes almost unlistenable. I haven't tested with wired headphones yet due to unavailability. Understand this is a niche bug but wanted to bring it up. Happens with both Airpods Pro 1 and 2. 

**How To Reproduce**

1. Open Jellyfin Roku app on Roku, start playing any title.
2. Connect Bluetooth headphones to phone
3. Open Roku App
4. Select private listening button under Remote section
5. Play title and wait for 10 minutes, audio will begin cutting out

**Expected behavior**
No audio cutting out

**Logs**

**Screenshots**

**Connection Information**
Server is local, HTTP connection

**Additional context**

**Comment by cewert** [comment] 2023-02-24 01:08
How many times have you observed this happening? Does this only happen with the jellyfin app? Have you confirmed this doesn't happen with other apps like youtube, netflix, HBO etc. when using your phone with bluetooth earbuds to watch roku? Have you tried different earbuds or a different phone?

I don't believe we've coded anything for this feature. I think it's more likely the phone/app, the earbuds, or some kind of interference.

**Comment by eric-schleicher** [comment] 2023-03-02 07:23
I have potentially similar problem, on a TCL Roku TV.   The Roku phone app shows that the audio switches over to the headset on the phone display (iOS) and stops playing on the TV, but nothing comes through on the headphones.  you can cycle it on and off; the behavior is the same.   audio on the TV works fine, and when you switch over to private listening...  nothing.

Also when the private listening is on the volume rocker on the phone does not register on the TV as a request on the TV to change the volume.

Jellyfin (1.6.3)  is the only Roku app i have trouble getting private listening to work.

Might this be the same issue?  or should i open a different issue?

**Comment by cewert** [comment] 2023-04-22 16:42
I'm unable to reproduce this bug using my android 12 phone with v1.6.3 of the jellyfin app. Switching on "private listening" makes the audio on my TV stop playing and instead comes through my phone and it works as expected both with bluetooth headphones and without. Perhaps this is an Apple thing? You both seem to be using Apple products.

@qman1198 are you still experiencing this issue?

@eric-schleicher were you able to get private listening to work?

> Also when the private listening is on the volume rocker on the phone does not register on the TV as a request on the TV to change the volume.

When private listening is turned on, the volume rocker on your phone does not control your TV. The whole point is for the roku app on your phone to output the audio instead of your TV. So the volume rocker on your phone will control your phones media output (without headphones) or your headphone volume (while connected to bluetooth headphones) but never your TV volume

**Comment by cewert** [comment] 2023-04-22 16:50
@qman1198 @eric-schleicher Can you tell me more about the video file you are watching when this bug occurs? I'm starting to think the reason I can't reproduce is because the video file I'm using to test is simple and can be direct played on both my roku and phone. If you could provide us with a sample file or the results from `ffprobe` or the settings used in handbrake to create the file that would be super helpful. Thanks!

**Comment by 1hitsong** [comment] 2024-02-19 17:05
Closing due to lack of follow up info.

**Closed as completed by 1hitsong** 2024-02-19 17:05 UTC
Labels: bug, info-needed
