### ISSUE TITLE
PGS Subtitles No Longer Work 

### ISSUE THREAD

**Issue by rbrowning85** [jellyfin-archive/jellyfin-roku-legacy#1983] opened 2024-10-09 04:24 UTC
Since the latest update when I try to turn on PGS subtitles, the app glitches and then skips to the next episode.

**Comment by cewert** [comment] 2024-10-09 11:24
Hopefully a duplicate of #1975. Please reopen if 2.1.7 doesn't fix your issue

**Closed as completed by cewert** 2024-10-09 11:24 UTC
Labels: bug
