### ISSUE TITLE
v1.6 Build 2 crashes when scrolling episode list on Shows with more than 27 episodes

### ISSUE THREAD

**Issue by TommyNorthAL** [jellyfin-archive/jellyfin-roku-legacy#910] opened 2022-12-19 14:56 UTC
**Software Versions**
Jellyfin Server Version: 10.8.8
Roku Client Version: 1.6 Build 2

**Describe the bug**
When scrolling thru the episode list on a show with more than 27 episodes, it crashes and returns to
the Roku homepage. Observed first crash is after scrolling from episode 27 to episode 28.  My testing was to
then restart the Roku and it repeated any number of times.  After a restart, I did not experience the issue with
a show that has fewer episodes, shows with 21 did not crash when scrolling all the way thru the list.  Without restarting
I had trouble with shows with many fewer episodes.
The specific show I had trouble with is Perry Mason, an old B&W standard def show, each one about 50 minutes. 

**How To Reproduce**
1. Select a show and season with more than 27 episodes
2. Open the season, showing the episode list
3. Scroll down repeatedly, for me past episode 27
4. Bug occurs

**Expected behavior**
I have not experienced the crash on prior releases, but I cannot say I ever specifically tested it.

**Logs**
None found (server logs, I don't know how to do Roku log

**Screenshots**
N/A.

**Connection Information**
server and Roku are on same WiFi

Is server connection http or https? 
it's just a port on local server

**Additional context**
This is a real problem, I hope you can fix quickly

**Comment by jimdogx** [comment] 2022-12-19 15:10
If you're able to get the logs from the Roku when it crashes that would be great:

https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md#bugcrash-reports

If not, it sounds like it's easy enough to reproduce.  Thanks 👍

**Comment by TommyNorthAL** [comment] 2022-12-19 15:17
I am not Roku developer, but I looked at how to get in developer mode and I can do that, I think, but if you can reproduce that would be much better to me. My development work is all high level stuff.

**Comment by ApexArray** [comment] 2022-12-19 19:45
I also saw this issue, but it was only when hovering over an episode without a community rating (no star or rating number). Is that also the case for you?

In my situation, the debugger pointed to [TVListDetails.brs#L53](https://github.com/jellyfin/jellyfin-roku/blob/unstable/components/tvshows/TVListDetails.brs#L53). The `star` and `communityRating` nodes do not exist for these episodes, so it throws an error `Invalid value for left-side of expression`.

I'm a little confused because the if statement should prevent items without a community rating from hitting line 53, right? But for some reason, there appears to be a mismatch between `itemData` and the current UI node. Perhaps due to some sort of race condition.

I fixed it by replacing [TVListDetails.brs#L57](https://github.com/jellyfin/jellyfin-roku/blob/unstable/components/tvshows/TVListDetails.brs#L57) with the following.

```
m.top.findnode("rating").visible = false
```

However, it's probably best to fix the root cause and ensure `itemData` always matches the currently selected UI node.

**Comment by TommyNorthAL** [comment] 2022-12-19 21:30
In my case, almost none of the episodes have ratings, and not any near where it crashes.

Tommy
________________________________

**Comment by ApexArray** [comment] 2022-12-19 21:48
Interesting. I loaded a TV show season with 33 episodes (and no community ratings) and was able to browse through each one without any issues. So I guess thee issue I was seeing only occurs when moving from a TV show with a rating to one without it. I

I wonder if the underlying issue is also affecting other properties. Can you spot any differences in the episode that causes the crash (e.g., air date, audio/video encoding track)?

**Comment by TommyNorthAL** [comment] 2022-12-19 22:44
I'm at a loss, but here is what I can report, have tried to be methodical:

  1.  The only show I have trouble with is Perry Mason, each season has 30 episodes, very few have viewer ratings.
  2.  I tried any number of other shows, with episodes of 20-22, and no problems.
  3.  The show in various seasons of Perry Mason crash on the same episode for that season each time, but for instance in season 1 it is episode 28 if scrolling down, episode 18 if scrolling up (from last to beginning). This absolutely repeats after restarting app or restarting roku, it's always those episodes for that season. But for season 2, also 30 episodes, it is episode 2 if scrolling down, 24 if scrolling up, repeatably.
  4.  In terms of watched/unwatched, season 1 has 8 episodes unwatched, all 30 in season 2 are unwatched.
  5.  I delete the app from the roku and reinstalled it, no change, not even in which episode crashed it.
  6.  To emphasize, this is not trying to watch an episode, but merely trying to scroll to it or past it in the episode listing of the show season.
  7.  Each of these shows plays fine on my server (PC). In fact, episode 18 in season 1 that crashes when scrolling last to beginning direction is an episode I watched previously, but before latest version of Roku/JF.
  8.  Jellyfin/server version 10.8.8, roku 11.5.0 build 4312, jellyfin/roku 1.6 build 2
  9.  Server log doesn't show anything that looks like errors
  10.

**Comment by ApexArray** [comment] 2022-12-19 23:42
Okay, I think I have it narrowed down. In my scenario:
- Scrolling from episode 1 (w/ rating) to episode 2 (no rating) causes the crash
- I inspected the `itemData` object found it contains data for episode 14 (w/ rating), even though it is very far away on the list.
- So `itemContentChanged()` is regularly called for items off screen (i.e., updating the "Ends at" time). But the code is trying to update the currently selected item via `m.top.findNode`

I think the solution is to grab references to those nodes during `init()` like this
![image](https://user-images.githubusercontent.com/91706106/208548667-475f2d02-3780-40c6-8a28-4b3720959a6f.png)

And then update the referenced variables during `itemContentChanged()` like this
![image](https://user-images.githubusercontent.com/91706106/208548709-fc677395-da6f-4f75-b6c7-ec96d6de1e0a.png)

At least that's working for me so far. I'm happy to submit a PR or add additional evidence if needed.

Any thoughts from the devs?

**Comment by 1hitsong** [comment] 2022-12-20 02:24
@ApexArray You were 100% on the money for us needing to move the findnode functions up. However, the core fix for this is checking if the m.rating node exists is valid before we reference it in the removeChild function.

**Comment by ApexArray** [comment] 2022-12-20 03:09
> However, the core fix for this is checking if the m.rating node exists is valid before we reference it in the removeChild function.

This wouldn't have made a difference in my scenario. The exception occurred on `m.star.visible = true`. because the star node had already been (properly) deleted for that episode. Let me know if I'm missing anything there.

I started working on this here https://github.com/ApexArray/jellyfin-roku/tree/fix-tv-show-listing-crash. I'll check for any similar issues in the other components and open a PR.

P.S. Most of my experience is with private/closed source development, and I'm still new to open source collaboration. I welcome any feedback on communication/issue/PR etiquette. 😊

**Closed as completed** 2022-12-21 13:01 UTC
Labels: bug
