### ISSUE TITLE
Back button not working on SetServerScreen

### ISSUE THREAD

**Issue by Dimitrije-Ciric** [jellyfin-archive/jellyfin-roku-legacy#589] opened 2022-05-07 16:54 UTC
**Describe the feature you'd like**
When a user presses the back button on SetServerScreen, I think it would be more user-friendly to exit the app or to show an exit app dialog that will ask the user to exit the app.
On "Roku Developers" web page says that the app must exit the app or show an exit app dialog when the user presses the back button on the main scene. I know that SetServerScreen is not the main scene but in some parts of the user experience, it is.
I just suggest that this feature should be added.

**Comment by cewert** [comment] 2022-05-28 03:05
When first installing the app and you end up at `SetServerScreen` hitting back exits the app as you'd expect because it is the main scene. Or at least, it should.

Can be more specific about which scenarios you think hitting back in `SetServerScreen` should exit the app and which scenarios shouldn't?

**Comment by jimdogx** [comment] 2022-05-28 13:04
I think @Dimitrije-Ciric is referring to hitting "*" on the home screen, selecting "Change Server" and then hitting "Back".  In this case, nothing happens.  At least that's the only place I'm able to reproduce the issue so far.

**Comment by Dimitrije-Ciric** [comment] 2022-05-28 19:02
I tried again. Firstly app automatically tried to connect to the server and while it was trying to connect I pressed back button and nothing happens. After it doesn't connect, I press the back button and then the app was breaks. @cewert @jimdogx

**Comment by cewert** [comment] 2022-05-28 19:30
Yea that's not good. I reinstalled to test it myself and the back button doesn't work at all. Even before trying to connect.

We'll need to fix that one as well as the one @jimdogx found. Thank you for telling us about this!

**Comment by Any-Fuel-5635** [comment] 2022-09-07 00:54
This should be fixed with PR #777, back will now refresh the server list, and home will be the only return function to the main Roku home screen. Back button will still return user to the Roku home screen once the user is logged in. Hopefully this is the resolution you were looking for. The PR is still under review, but seems to function normally on my end (have tested it on multiple devices).

**Closed as completed** 2022-09-08 19:19 UTC
Labels: bug, regression
