### ISSUE TITLE
Music library does not populate

### ISSUE THREAD

**Issue by BradB58** [jellyfin-archive/jellyfin-roku-legacy#802] opened 2022-09-21 04:21 UTC
**Describe the bug**

My music library is complete and plays fine on the web page, but displays as empty on Roku app. All music in the folder is mp3 and there are 2,292 tracks total. I tried deleting the library and adding it again with no luck. The first time I was able to see one subfolder displayed on the Roku (it should have shown 15) but when I clicked on the folder it was empty. After deleting the music library and adding it again, this time the library showed on the Roku as completely empty; not even having the one folder it had before. Message on the screen said "This CollectionFolder contains no items."

Server: RaspberryPI             
Version: 10.8.4
Operating System: Linux
Architecture: Arm

Client: Roku3 
Jellyfin Roku 1.5.0

**Additional context**

I have another library which also contains all mp3 music but only 478 tracks. This one displays and plays fine on the Roku. This causes me to wonder if the large number of tracks has something to do with the issue?

**Comment by candry7731** [comment] 2022-09-22 15:58
Did you try a different view option? click "*" then toggle the different view, filter options. If you could provide some images or video of what you are seeing that will be helpful in fixing the issue

Report back.

**Comment by BradB58** [comment] 2022-09-26 03:30
Thanks. I had not noticed those view options. Still getting used to using Jellyfin. So that does help narrow the problem down a little. On default view, my screen looks like this: 

![IMG_172049](https://user-images.githubusercontent.com/95951717/192185082-54c82906-c7e1-4fc4-a499-58383bd54cbb.jpg)

When I tried artist view, all my stuff showed up fine! 

![IMG_20220925_193934](https://user-images.githubusercontent.com/95951717/192185521-af5c9e18-b9e0-4bb2-b342-db04992ad071.jpg)

Album view also worked fine:

![IMG_20220925_194007](https://user-images.githubusercontent.com/95951717/192185703-fc987891-8d04-42b2-b7b7-abb6f83ae363.jpg)

So apparently the problem is only with default view. 

Note: My folder hierarchy has an extra level for genre - i.e. /Music/Genre/Artist/Album/Song.mp3. I don't know if that would be causing the issue. The reason I mention that, is that I read about the music organization scheme here: https://jellyfin.org/docs/general/server/media/music.html 
The example given is /Music/Artist/Album, but it doesn't really say you can't have an extra level. I have always used the genre level and never had an issue. Worked fine for me on Emby as well as any music app I've ever used.

**Comment by jwor80** [comment] 2022-09-28 20:00
I'm seeing the same issue on my Roku with JellyFin.

**Comment by jwor80** [comment] 2022-09-28 21:06
Are you also missing the ability to view the genres for music?  I use the same folder structure for my music.  The idea is that I don't need to make a playlist as I can select a genre and play all music within that genre.

https://github.com/jellyfin/jellyfin-roku/issues/807

**Comment by BradB58** [comment] 2022-09-29 00:22
jwor80 Yes. I can confirm there is no ability to view genres for music. I also notice that I cannot access or play my playlists from the Roku app but I can from the browser app. The Roku app is new, so I guess there are some features they haven't got implemented yet.

**Comment by 1hitsong** [comment] 2022-09-29 12:25
I believe the issue is your folder structure. This was my first pass at getting music working, and I built it to spec. That being said, I'm roughly 90% done reworking the logic for the default view. This update is a rebuild of how the web app polls for data, so once completed, Roku and Web should be 100% the same list wise.

> The Roku app is new, so I guess there are some features they haven't got implemented yet.

💯 That's it. Infact, this release was the first time we supported music playback. We'll get to it, but right now our primary focus is a rock solid foundation for music playback that we can then add new and exciting features on top of.

**Comment by jwor80** [comment] 2022-09-29 13:31
That is all good news.  I didn't realize the roku app was newer or that music just started working in the last version.  I've been using Emby for years and have given Jellyfin a couple of tries in the past and was testing it out again to see if it would work for me.

**Comment by 1hitsong** [comment] 2022-10-07 12:22
We expect this issue to be resolved with newly merged code from #811 which will be part of the next release.

If after the next release the issue continues, please open a new issue.

**Closed as completed by 1hitsong** 2022-10-07 12:22 UTC
Labels: bug
