### ISSUE TITLE
Next Up - Long press on OK just plays media, which is different from other sections on home screen.

### ISSUE THREAD

**Issue by roast1880** [jellyfin-archive/jellyfin-roku-legacy#1411] opened 2023-10-10 23:52 UTC
## Software Versions

- Jellyfin Server Version:  10.8.9
- Roku Client Version:  1.6

## Describe the bug
*Roku client on a Roku TV (TCL), UI alignment for "Next Up"

Long press for OK button is not the same in "Next Up" 

Continue Watching
          OK button (long press)
                   Resume playing at x:xx:xx
                   Start over from the beginning.
                   Watched
                   Go to series
                   Go to season
                   Go to episode
         
         '*' button (long press)
                 Search
                 Change server
                 Sign out
                 Settings
                 Profile: username@http://
Next Up 
          OK button (long press)
                   MEDIA PLAYS, no menu, does not go to show/season/episode
         
          '*' button (long press)
                 Search
                 Change server
                 Sign out
                 Settings
                 Profile: username@http://
Favorites
          OK button (long press)
                   goes to movie
         
           '*' button (long press)
                 Search
                 Change server
                 Sign out
                 Settings
                 Profile: username@http://
Latest in Movies
          OK button (long press)
                   goes to movie
         
         '*' button (long press)
                 Search
                 Change ... (same as others)
Latest in  Shows*
          OK button (long press)
                   goes to show
         
          '*' button (long press)
                 Search
                 Change ... (same as others)

## How To Reproduce

1. Go to main menu, press and hold OK on the different sections and you'll see Next Up doesn't behave the same way.

## Expected behavior
Next Up would have similar features to continue watching.
          OK button (long press)
                   Resume playing at x:xx:xx
                   Start over from the beginning.
                   Watched
                   Go to series
                   Go to season
                   Go to episode
                   
## Logs
N/A

## Screenshots
n/A

## Connection Information

- Is server local or remote? Local
- Is server connection HTTP or HTTPS? HTTP

## Additional context
THANKS! :D

**Comment by cewert** [comment] 2023-10-13 15:13
This isn't a bug since the menu was only added to the "Continue Watching" row by design. Closing in favor of #613 

PS: I don't know what you mean by "long press on OK button". We don't have any special function tied to long pressing the okay button. Tapping the okay button will produce the same results.

**Closed as completed by cewert** 2023-10-13 15:13 UTC
Labels: duplicate, enhancement

**Comment by roast1880** [comment] 2023-10-14 16:30
> This isn't a bug since the menu was only added to the "Continue Watching" row by design. Closing in favor of #613
> 
> PS: I don't know what you mean by "long press on OK button". We don't have any special function tied to long pressing the okay button. Tapping the okay button will produce the same results.

Sorry, different apps have different ways of using the buttons. I took a behavior from another app and assumed it was configured in Jellyfin the same way.
