### ISSUE TITLE
Can't change users

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#1372] opened 2023-09-13 08:43 UTC
## Software Versions

- Jellyfin Server Version:  10.8.10
- Roku Client Version:  1.6 build 6

## Describe the bug
I'm logged in as user1. If I choose another user I am still logged in as. user1. 

## How To Reproduce
1. Be logged in as user1
2. Press the `*` button to get the menu
3. Choose "change server"
4. Select the server
5. Submit
6. Choose user2
7. Find yourself back at the home screen which says it's still logged in as user1

## Expected behavior
I'm either challenged for a password, or I'm now logged in as user 2.

## Connection Information

- Is server local or remote? Remote 
- Is server connection HTTP or HTTPS? Https

## Additional context
I'm usually logged in as user1. I'm not sure whether I've ever logged in as user2 before on this client. Perhaps I haven't.
The "Profile:user1@...." menu item doesn't appear to do anything.

**Comment by cewert** [comment] 2023-09-13 13:23
I can't reproduce this using 1.6.6. I have two public users with no password. Every time I Change Server and select the other user everything works as expected.

**Comment by tremby** [comment] 2023-09-13 21:57
Both my users have passwords. It's likely I've never logged in as user2.

So is the bug perhaps that no "enter password" screen is triggered if the password isn't already known?

**Comment by cewert** [comment] 2023-09-13 22:01
It's possible. I'll try making a dummy user with a password and give it another shot when I get time.

**Comment by cewert** [comment] 2023-09-13 22:59
I was able to reproduce. I have an idea what's going on I'll look into this.

Edit: Fixed in #1374

**Closed as completed** 2023-09-21 17:01 UTC
Labels: bug
