### ISSUE TITLE
Continue Watching for next Show episode is missing from Roku

### ISSUE THREAD

**Issue by TommyNorthAL** [jellyfin-archive/jellyfin-roku-legacy#1196] opened 2023-04-12 21:42 UTC
## Software Versions

- Jellyfin Server Version:  10.8.8
- Roku Client Version:  1.6.4

## Describe the bug

Jellyfin home screen used to show the next episode for Show, but now is completely missing. Have to go
to Shows, select season, scroll to first unwatched episode.

## How To Reproduce

Self explanatory from Description?

## Expected behavior

See Description.

## Connection Information

- Is server local or remote? Local
- Is server connection HTTP or HTTPS? unsecure

## Additional context

Roku system updated today, to version 11.5.0 6040, but the Continue playing next episode worked yesterday.

**Comment by p37307** [comment] 2023-04-14 09:49
Seems like a duplicate of  https://github.com/jellyfin/jellyfin-roku/issues/1184

**Comment by cewert** [comment] 2023-04-14 12:18
Closing in favor of #1184. Thank you for the bug report!

**Closed as completed by cewert** 2023-04-14 12:18 UTC
Labels: bug, duplicate
