### ISSUE TITLE
Allow to filter movies by Genres

### ISSUE THREAD

**Issue by kamanwu** [jellyfin-archive/jellyfin-roku-legacy#447] opened 2021-05-16 14:38 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For now, when filter movies, there is only ONE filter which have 2 options: all / favorites.  

Could we add a new filter: Genres so that we could list movies like: Action / Adventure / Animation / ....

I know there are lots of other filters like: Video Types / Years, but I think Genres filter is an essential filter.

**Comment by anthonylavado** [comment] 2021-05-16 22:36
Duplicate of #5. It is something being looked at :-)

**Closed as completed** 2021-05-16 22:37 UTC
Labels: duplicate
