### ISSUE TITLE
SRT subtitles not displayed when "Text Subtitles Only" option is enabled

### ISSUE THREAD

**Issue by dathbe** [jellyfin-archive/jellyfin-roku-legacy#1627] opened 2024-01-09 20:27 UTC
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  2.0.1 (2.0 build 1)

## Describe the bug
When the "Text Subtitles Only" setting is enabled, the app hides SRT subtitles, which are text subtitles.

## How To Reproduce

1. Enable "Text Subtitles Only" (Settings>Playback>Text Subtitles Only)
2. Play a movie with SRT subtitles
3. Press the up button to enter the option menu
4. SRT subtitles are not available

## Expected behavior

"Text Subtitles Only" should only hide graphic subtitles (e.g., PGS)

## Logs

N/A

## Screenshots

![compare](https://github.com/jellyfin/jellyfin-roku/assets/14321825/619dcea3-7f61-42d6-9fb7-a18202565c94)

## Connection Information

- Is server local or remote? Local
- Is server connection HTTP or HTTPS? HTTPS

**Comment by 1hitsong** [comment] 2024-01-12 01:37
Found the root cause. Working on a fix.

The code only allows a subtitle track to have 1 type. forced, default, text, or normal. In this case, the subtitle track is both default AND text, but only the default will get picked up.

![image](https://github.com/jellyfin/jellyfin-roku/assets/3330318/86af460c-d4f5-4e3a-ad30-3b5819501c77)

**Comment by 1hitsong** [comment] 2024-01-12 02:19
@dathbe Please test this PR and see if it resolves your issue: https://github.com/jellyfin/jellyfin-roku/pull/1633

**Comment by dathbe** [comment] 2024-01-12 05:10
Confirmed that PR 1633 fixes this issue for me.  Text subtitles are now shown with the "Text Subtitles Only" option enabled, even if they are set to default.  Thanks!

**Comment by 1hitsong** [comment] 2024-01-12 20:47
Fixed by #1633

**Closed as completed by 1hitsong** 2024-01-12 20:47 UTC
Labels: bug
