### ISSUE TITLE
Implement library type: folders

### ISSUE THREAD

**Issue by mushkevych** [jellyfin-archive/jellyfin-roku-legacy#287] opened 2020-11-08 23:31 UTC
**Describe the feature you'd like**
Today, both *Jellyfin* and *Jellyfin beta* report:
`This library type is not yet implemented: folders`

**Comment by anthonylavado** [comment] 2020-11-09 08:11
Duplicate of #284.

**Comment by neilsb** [comment] 2020-11-09 08:21
I am not sure #284 will allow viewing of "On Disk Folders", if that is what this ticket is referring to...

**Comment by anthonylavado** [comment] 2020-11-10 05:12
Ah I suppose. @mushkevych Would you mind clarifying just exactly what type of folder it is?

**Comment by mushkevych** [comment] 2020-11-10 06:38
"Folders" allow to browse shared network filesystem and play media files. I am thinking about as of FTP or Samba.

**Comment by jcdick1** [comment] 2020-11-13 03:57
Is the OP's idea to have the client "stepping out" of the JF ecosystem to navigate CIFS/NFS or other network shares directly?

**Comment by neilsb** [comment] 2020-11-13 07:45
Pretty sure this is just if you enable folder view within Jellyfin. 

The client handles folders in Mixed Content libraries already, so should be fairly straightforward to get it to handle the top level Folders Collection if enabled.

**Comment by mushkevych** [comment] 2020-11-14 06:20
@neilsb I believe you are correct. If I am not mistaken, the "Folders" library appears after selecting the option below 
(Admin -> Libraries -> Display -> Display a folder view to show plain media folders)
![image](https://user-images.githubusercontent.com/1039233/99141244-4a18eb00-25fe-11eb-82c1-1a03ac57a76b.png)

**Closed as completed** 2021-04-13 13:44 UTC
Labels: enhancement
