### ISSUE TITLE
Collections not supported version 9.X

### ISSUE THREAD

**Issue by CubeyGlyph** [jellyfin-archive/jellyfin-roku-legacy#438] opened 2021-05-01 20:04 UTC
**Describe the bug**
I have heard of the bug with version 10 caused by a Roku update but the same bug appears to be affecting version 9, I can’t open any collections on Roku app.

**To Reproduce**
Attempt to open collection
See error

**Expected behavior**
Should open collection and show movies within

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by anthonylavado** [comment] 2021-05-02 06:17
Duplicate of #427. Fixed in beta channel already, main channel update scheduled to Tuesday by Roku.

**Closed as completed** 2021-05-02 06:18 UTC
Labels: bug, duplicate
