### ISSUE TITLE
Unable to open v2.0.0 on Roku OS 12.5.0 build 4178-50

### ISSUE THREAD

**Issue by 2john978** [jellyfin-archive/jellyfin-roku-legacy#1595] opened 2023-12-23 20:57 UTC
## Software Versions

- Jellyfin Server Version:  10.8.10
- Roku Client Version:  2.0.0
- Roku streaming stick 3810X running version 12.5.0 build 4178-50

## Describe the bug

Jellyfin app crashes rather than opens. Clicking the icon, the Roku display changes to display the word Jellyfin for about one second, then returns to Home screen without Jellyfin opening.

## How To Reproduce

1. Go to Roku Home screen
2. Click on the Jellyfin app icon
3. Bug occurs

## Expected behavior

Clicking the icon, the Jellyfin app interface should open.

## Connection Information

- Is server local or remote?  Server is local and on the same wifi as the Roku client.
- Is server connection HTTP or HTTPS? Server uses HTTP.

## Additional context

Version 1.6.6 had run with no issues on the same configuration.  
Was able to switch to developer mode and install version 1.6.6, which runs as expected.

**Comment by cewert** [comment] 2023-12-23 21:01
It's possible you're running into the bug fixed in #1574. It was a crash caused by the registry migrations that are run when the app is first started.

Can you sideload the [`2.0.z` branch](https://github.com/jellyfin/jellyfin-roku/tree/2.0.z) and see if that fixes the crash for you?

**Comment by 2john978** [comment] 2023-12-23 21:35
Yes, I sideloaded v2.0.0 and it opens and runs perfecting. 
I'll use this dev version until the next version is released resolving bug #1574. 
Thank you for your help!

Not sure if I should 'close with comment' or not. 
John

**Comment by cewert** [comment] 2023-12-23 21:47
Glad you got it working. Thanks for testing and reporting back!

**Closed as completed** 2023-12-23 21:48 UTC
Labels: bug
