### ISSUE TITLE
Faster scrolling and skipping to titles by their first letter

### ISSUE THREAD

**Issue by Germs2004** [jellyfin-archive/jellyfin-roku-legacy#364] opened 2021-02-09 03:38 UTC
**Is your feature request related to a problem? Please describe.**
Scrolling a long list of videos takes a long time on Roku.  If you hold the down button on the remote, the list pauses after it scrolls down 5-10 lines until you release the down button.  Then it loads more items so you have to hold the down button again to continue scrolling.  It takes forever to get to the bottom of the list.

**Describe the solution you'd like**
Add A-Z alphabet letters to the right side of the list.  If we move our cursor over to the rightmost movie, and press right again, our cursor should highlight the letter "A" on the alphabet.  Then, if we then push down, it should highlight "B" and instantly scroll the videos on the left side of the screen to the ones beginning with "b".  This allows us to quickly scroll to "Z" or whatever letter we want.  Pushing left from the alphabet should move our cursor over to the video list where we have scrolled.

Also, please improve regular scrolling so that it does not pause after 5-10 lines of holding the down button.  It should scroll quickly and smoothly without hesitation all the way to the bottom of the list.

**Additional context**
Plex for Roku has these features already.

**Comment by anthonylavado** [comment] 2021-02-09 07:35
>Plex for Roku has these features already.

😐

**Comment by Germs2004** [comment] 2021-02-09 14:01
> > Plex for Roku has these features already.
> 
> 😐

Sorry, I didn't say that to hurt feelings, just to inform that if the Jellyfin developers want to see an example of the feature working, they could look at the Plex app.  It gives them a resource to study when planning their own implementation.

**Comment by cewert** [comment] 2021-02-09 14:20
Duplicate of #224. Please make a separate issue for the "faster scrolling"

**Closed as completed by cewert** 2021-02-09 14:20 UTC
Labels: enhancement
